{
 "title": "Proxy Logs",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({different=~\".+\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "Requests with discrepancies in responses",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "{different=~\"1\"} | json | line_format \"{{.rpc_method}} - {{.status}} - {{.request_body}}\""
    }
   ]
  },
  {
   "title": "Full logs",
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{different=~\".+\"}"
    }
   ]
  }
 ]
}